services:
    helpers_bundle.helper.breadcrumbs:
        class: Adamski\Symfony\HelpersBundle\Helper\BreadcrumbsHelper
        arguments:
            - "@router"

    Adamski\Symfony\HelpersBundle\Helper\BreadcrumbsHelper:
        alias: helpers_bundle.helper.breadcrumbs

    helpers_bundle.helper.directory:
        class: Adamski\Symfony\HelpersBundle\Helper\DirectoryHelper
        arguments:
            - "@service_container"

    Adamski\Symfony\HelpersBundle\Helper\DirectoryHelper:
        alias: helpers_bundle.helper.directory

    helpers_bundle.helper.mailer:
        class: Adamski\Symfony\HelpersBundle\Helper\MailerHelper
        arguments:
            - "@mailer"
            - "@twig"
            - "%helpers.mailer.default_sender%"

    Adamski\Symfony\HelpersBundle\Helper\MailerHelper:
        alias: helpers_bundle.helper.mailer

    helpers_bundle.helper.notification:
        class: Adamski\Symfony\HelpersBundle\Helper\NotificationHelper
        arguments:
            - "@session.flash_bag"

    Adamski\Symfony\HelpersBundle\Helper\NotificationHelper:
        alias: helpers_bundle.helper.notification

    helpers_bundle.helper.pagination:
        class: Adamski\Symfony\HelpersBundle\Helper\PaginationHelper
        arguments:
            - "@session"
            - "@router"

    Adamski\Symfony\HelpersBundle\Helper\PaginationHelper:
        alias: helpers_bundle.helper.pagination

    helpers_bundle.helper.pdf:
        class: Adamski\Symfony\HelpersBundle\Helper\PDFHelper
        arguments:
            - "@helpers_bundle.helper.directory"
            - "@twig"

    Adamski\Symfony\HelpersBundle\Helper\PDFHelper:
        alias: helpers_bundle.helper.pdf

    helpers_bundle.twig.extension.breadcrumbs:
        class: Adamski\Symfony\HelpersBundle\Twig\BreadcrumbsExtension
        arguments:
            - "@helpers_bundle.helper.breadcrumbs"
            - "@translator"
        tags:
            - { name: twig.extension }

    helpers_bundle.twig.extension.notification:
        class: Adamski\Symfony\HelpersBundle\Twig\NotificationExtension
        arguments:
            - "@helpers_bundle.helper.notification"
        tags:
            - { name: twig.extension }

    helpers_bundle.twig.extension.pagination:
        class: Adamski\Symfony\HelpersBundle\Twig\PaginationExtension
        tags:
            - { name: twig.extension }

    helpers_bundle.twig.extension.asset_hash:
        class: Adamski\Symfony\HelpersBundle\Twig\AssetHashExtension
        arguments:
            - "@templating.helper.assets"
            - "@helpers_bundle.helper.directory"
        tags:
            - { name: twig.extension }
